### ISSUE TITLE
Incorret usage

### ISSUE THREAD

**Issue by kedira2bala** [Harmenszoon/dllinjector#1]
Why when i compile this and open my injector show this text ? : "Incorret usage" like this image http://prntscr.com/jouut8

**Comment by kedira2bala** [comment]
![download 1](https://user-images.githubusercontent.com/39790367/40766251-3fcef33e-6485-11e8-909f-a65dc767d365.png)

**Comment by kedira2bala** [comment]
how to solve this?

**Comment by Loadable** [comment]
Drag .dll file onto .Exe
